"""Miner — session mining -> permanent playbook rules (NOTES.md Add 2).

Reads run logs (and state.db if available) across runs, finds REPEATED failure
patterns, and converts each into a playbook rule so it stops recurring. The
automated version of the by-hand fixes in CONNECTORS_DESIGN.md / PHILOSOPHY.md.
"""
import glob
import os
import re
import sqlite3

# pattern -> (regex, rule to add to the playbook when the pattern recurs)
PATTERNS = [
    ("pip_install_preinstalled",
     r"(uv )?pip install .*earthengine-api|pip install .*pymupdf",
     "earthengine-api and pymupdf are PREINSTALLED in the image. Never pip/uv "
     "install them — `import ee` / `import fitz` just work."),
    ("hand_rolled_ndvi",
     r"reduceRegion|ImageCollection\([^)]*MODIS|Sentinel|NDVI.*reduce",
     "Do NOT hand-write an NDVI/EE reduction. Use greenness.trend / the relevant "
     "connector; run its --describe first."),
    ("mkdir_workdir",
     r"mkdir.*/opt/data/work|Permission denied.*/opt/data|Read-only file system",
     "Create the work dir first: `mkdir -p /opt/data/work`, and write connector "
     "--out only there (connector/input mounts are read-only)."),
    ("module_not_found",
     r"ModuleNotFoundError: No module named '(ee|fitz)'",
     "If `ee`/`fitz` import fails, you are on the wrong interpreter — the connector "
     "self-heals to the venv python; just run `python /opt/data/connectors/<name>.py`."),
    ("global_firms_query",
     r"filterBounds\(.*world|FIRMS.*global|numPixels=1e",
     "Query fire/occurrence NEAR the AOI/points, never globally — clip to the bbox."),
]


def _scan_text(text, counts, hits):
    for name, rx, _rule in PATTERNS:
        m = re.findall(rx, text, flags=re.IGNORECASE)
        if m:
            counts[name] = counts.get(name, 0) + len(m)
            hits.setdefault(name, 0)
            hits[name] += 1        # number of distinct sources the pattern appears in


def mine(runs_glob, statedb=None, min_sources=1):
    """Return playbook rules for patterns seen in >= min_sources runs."""
    counts, hits = {}, {}
    logs = sorted(glob.glob(runs_glob))
    for lg in logs:
        try:
            _scan_text(open(lg, errors="ignore").read(), counts, hits)
        except OSError:
            continue
    # best-effort state.db scan (schema-agnostic: dump text-ish columns)
    if statedb and os.path.exists(statedb):
        try:
            con = sqlite3.connect(f"file:{statedb}?mode=ro", uri=True)
            for (tbl,) in con.execute(
                    "select name from sqlite_master where type='table'").fetchall():
                try:
                    rows = con.execute(f"select * from '{tbl}' limit 2000").fetchall()
                except sqlite3.Error:
                    continue
                _scan_text("\n".join(str(r) for r in rows), counts, hits)
            con.close()
        except sqlite3.Error:
            pass

    rules = []
    for name, rx, rule in PATTERNS:
        if hits.get(name, 0) >= min_sources:
            rules.append({"pattern": name, "occurrences": counts.get(name, 0),
                          "in_n_sources": hits.get(name, 0), "rule": rule})
    return {"scanned_logs": len(logs), "rules": rules}


def write_playbook_rules(mined, path):
    with open(path, "w") as f:
        f.write("# Mined playbook rules (auto-generated by the Miner)\n\n")
        f.write(f"Scanned {mined['scanned_logs']} run log(s). "
                f"{len(mined['rules'])} recurring pattern(s) -> rules:\n\n")
        for r in mined["rules"]:
            f.write(f"- **{r['pattern']}** (seen {r['occurrences']}x across "
                    f"{r['in_n_sources']} run(s)): {r['rule']}\n")
    return path
